query latest10Posts {
  post(limit: 10, orderBy: {publishedAt: DESC_NULLS_LAST}, offset: 0) {
    slug
    title
    author {
      id
      labelName
    }
    likesAggregate {
      aggregate {
        count
      }
    }
  }
}
