query my10PostsEach {
  post(limit: 10, order_by: {published_at: desc_nulls_last}, offset: 0) {
    slug
    title
    publish_at
    published_at
    author {
      id
      label_name
    }
    likes_aggregate {
      aggregate {
        count
      }
    }
  }
}
